name: connectivity_service
description: A service for managing internet connectivity in a Flutter app.
version: 1.0.2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.2
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
