name: connectivity_service
description: A service for managing internet connectivity in a Flutter app.
version: 1.0.6

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  connectivity_plus: ^6.1.0
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
